### ISSUE TITLE
Roadmap to v0.1

### ISSUE THREAD

**Issue by fraz3alpha** [fraz3alpha/running-challenges#1]
Version `0.1` will be the first to be widely published in the Chrome Web Store. To get to that version we need to make sure we have a few things that makes it easy to use so that first users don't get frustrated.

- [x] A nice help page
- [x] Sensible options page with instructions, also linking to the help page
- [x] Links from normal athlete pages to link to the one where the stats are displayed
- [x] Explicit alphabeteer alphabet selection, explaining why that is the one we are using, and what options there might be in the future
- [x] Google analytics to see if anyone is actually using the plugin
  - Added Google Analytics ID to the Web Store so we can track how many people are browsing it there

**Comment by fraz3alpha** [comment]
Push `v0.1.0.5` to the webstore and made it public!
